# Generated by Django 5.2.1 on 2025-05-24 07:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Saldo Inicial')),
            ],
            options={
                'verbose_name': 'Cartera',
                'verbose_name_plural': 'Carteras',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('tipo', models.CharField(choices=[('I', 'Ingreso'), ('G', 'Gasto')], max_length=1, verbose_name='Tipo')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('cartera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='gestion.cartera', verbose_name='Cartera')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='gestion.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'ordering': ['-fecha'],
            },
        ),
    ]
